version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_concerts_songs
    ports:
      - "8000:8000"
    environment:
      - MONGODB_SERVICE=mongodb
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_PORT=27017
    depends_on:
      - mongodb
    networks:
      - backend-net

  mongodb:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=api_concerts_songs
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
      - mongodb
    networks:
      - backend-net

volumes:
  mongo-data:

networks:
  backend-net:
    driver: bridge
